name: Prune Registry
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  prune-images:
    runs-on: ubuntu-latest
    steps:     
      - name: Extract repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GH_TOKEN_PRUNE }}
          container: ${{ env.REPO_NAME }}
          dry-run: false
          keep-younger-than: 0 # days
          keep-last: 6
          prune-untagged: true
